# LAB 2: NUMPY, PANDAS VÀ MATPLOTLIB NÂNG CAO

# 1. NUMPY

In [5]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Lấy số 3
x[2]

array([3, 4, 5, 6, 7])

In [6]:
# Lấy 1 2 3
x[:3]

array([1, 2, 3])

In [7]:
# Lấy từ 3 đến 8
x[2:7]

array([3, 4, 5, 6, 7])

In [8]:
# 7, 8
x[-2:]

array([7, 8])

In [14]:
# 2, 4
x[2], x[4]

(np.int64(3), np.int64(5))

In [16]:
data = [[1, 2], [3, 4], [5, 6]]
mang = np.array(data)
print(mang)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
mang[0, 1]

np.int64(6)

In [24]:
mang[2, 1]

np.int64(6)

In [27]:
mang[1:, :]

array([[3, 4],
       [5, 6]])

In [28]:
mang[1:]

array([[3, 4],
       [5, 6]])

In [29]:
mang[[1, 2], :]

array([[3, 4],
       [5, 6]])

In [30]:
mang[1: 3]

array([[3, 4],
       [5, 6]])

In [31]:
mang[-2:]

array([[3, 4],
       [5, 6]])

In [32]:
mang[:, 0]

array([1, 3, 5])

In [33]:
mang[[0, 2], 00]

array([1, 5])

In [34]:
mang[::2, 0]

array([1, 5])

In [37]:
x = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

x = np.array(x)

In [39]:
# Lấy 2 6 10 14
x[:, 1]

array([ 2,  6, 10, 14])

In [40]:
# Lấy 7 và 11
x[1:3, 2]

array([ 7, 11])

In [44]:
# Lấy 4 7 10
x[[0, 1, 2], [3, 2, 1]]

array([ 4,  7, 10])

In [46]:
# Lấy 16 15 14 13
x[3][::-1]

array([16, 15, 14, 13])

In [47]:
x[-1, -1::-1]

array([16, 15, 14, 13])

In [ ]:
# Bài tập Tết về nhà

# Cho ma trận = [
#    [99, 99 ,99],
#    [99, 99 ,99],
#    [99, 99, 99]
# ]

# Giả sử 0 = 1 và 1 là x 
# Nhận đầu vào từ phía x và 0 luân phiên
# Cho các bạn một cặp chỉ số
# Nếu phía x nhập ((0, 0)) thì ma trận trở thành
#   [
#    [X, 99 ,99],
#    [99, 99 ,99],
#    [99, 99, 99]
#   ]
# Nếu phía 0 nhập ((0, 0)) thì yêu cầu nhập lại và nếu không thì điền vào ma trận
# Thử thách của các bạn ở nhà ăn tết: Nếu ai đó có ba ô liên tiếp thì dừng trò chơi

In [ ]:
def print_board(board):
    for row in board:
        print(" ".join(map(str, row)))
    print()

def check_winner(board, player):
    for row in board:
        if all(cell == player for cell in row):
            return True

    for col in range(3):
        if all(board[row][col] == player for row in range(3)):
            return True

    if all(board[i][i] == player for i in range(3)) or all(board[i][2 - i] == player for i in range(3)):
        return True

    return False

def is_board_full(board):
    return all(cell != 99 for row in board for cell in row)

def main():
    board = [
        [99, 99, 99],
        [99, 99, 99],
        [99, 99, 99]
    ]

    current_player = 'X'

    while True:
        print_board(board)
        print(f"Lượt của {current_player}")

        try:
            row, col = map(int, input("Nhập vị trí (hàng, cột): ").split())
            if row < 0 or row > 2 or col < 0 or col > 2:
                print("Vị trí không hợp lệ. Vui lòng nhập lại.")
                continue

            if board[row][col] != 99:
                print("Ô đã được chọn. Vui lòng nhập lại.")
                continue

            board[row][col] = current_player

            if check_winner(board, current_player):
                print_board(board)
                print(f"{current_player} thắng!")
                break

            if is_board_full(board):
                print_board(board)
                print("Hòa!")
                break

            current_player = 'O' if current_player == 'X' else 'X'

        except ValueError:
            print("Đầu vào không hợp lệ. Vui lòng nhập lại.")

if __name__ == "__main__":
    main()

99 99 99
99 99 99
99 99 99

Lượt của X
99 99 99
99 99 99
99 99 X

Lượt của O
Ô đã được chọn. Vui lòng nhập lại.
99 99 99
99 99 99
99 99 X

Lượt của O
99 99 99
99 O 99
99 99 X

Lượt của X
Ô đã được chọn. Vui lòng nhập lại.
99 99 99
99 O 99
99 99 X

Lượt của X
Vị trí không hợp lệ. Vui lòng nhập lại.
99 99 99
99 O 99
99 99 X

Lượt của X
Vị trí không hợp lệ. Vui lòng nhập lại.
99 99 99
99 O 99
99 99 X

Lượt của X
Vị trí không hợp lệ. Vui lòng nhập lại.
99 99 99
99 O 99
99 99 X

Lượt của X
Vị trí không hợp lệ. Vui lòng nhập lại.
99 99 99
99 O 99
99 99 X

Lượt của X
X 99 99
99 O 99
99 99 X

Lượt của O
X O 99
99 O 99
99 99 X

Lượt của X
X O X
99 O 99
99 99 X

Lượt của O
Ô đã được chọn. Vui lòng nhập lại.
X O X
99 O 99
99 99 X

Lượt của O
X O X
O O 99
99 99 X

Lượt của X
X O X
O O X
99 99 X

X thắng!


In [ ]:
x = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
x = np.array(x)

# Lấy 4 5 6 
x[1]

array([4, 5, 6])

In [ ]:
# Lấy 2, 5
x[0][1], x[1][1]

(np.int64(2), np.int64(5))

In [ ]:
# Lấy 3, 4
x[0, 2], x[1, 0]

(np.int64(3), np.int64(4))

In [59]:
# Lấy 9, 6, 3
x[2][2], x[1][2], x[0, 2]

(np.int64(9), np.int64(6), np.int64(3))

In [61]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Lấy ra các mảng số chẵn

mang_chan = [num for num in x if num % 2 == 0]

print(mang_chan)

[2, 4, 6, 8, 10]


In [67]:
x = np.ones((3, 3))

In [68]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
x = np.arange(3)

In [71]:
np.arange(3)

array([0, 1, 2])

In [64]:
np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [73]:
x + y

array([0, 2, 4])

In [74]:
x = x.reshape((3, 1))

In [ ]:
# Tạo một mảng numpy có kích thước 150x5. Hãy tưởng tượng mảng này chứa 150 mẫu về chiều cao, cân nặng, tuổi, lương, GPA của sinh viên VLU

# Chia mảng bống cọt đầu tiên thành một biến có tên là X và cột cuối cùng thành Y

# Chia X thành X_train và X_test chứa 70% dữ liệu và chia y thành y_train và y_test, trong đó y_train chứa 70% dữ liệu

# Tạo 10 tập dữ liệu không chồng chéo của x_traintrain

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

data = np.random.rand(150, 5) 

X = data[:, :-1] 
Y = data[:, -1]   

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

num_splits = 10
split_size = len(X_train) // num_splits
X_train_splits = [X_train[i*split_size:(i+1)*split_size] for i in range(num_splits)]

print("Kích thước của X_train:", X_train.shape)
print("Kích thước của X_test:", X_test.shape)
print("Kích thước của y_train:", y_train.shape)
print("Kích thước của y_test:", y_test.shape)

for i, split in enumerate(X_train_splits):
    print(f"Kích thước của X_train_split {i+1}:", split.shape)

Kích thước của X_train: (105, 4)
Kích thước của X_test: (45, 4)
Kích thước của y_train: (105,)
Kích thước của y_test: (45,)
Kích thước của X_train_split 1: (10, 4)
Kích thước của X_train_split 2: (10, 4)
Kích thước của X_train_split 3: (10, 4)
Kích thước của X_train_split 4: (10, 4)
Kích thước của X_train_split 5: (10, 4)
Kích thước của X_train_split 6: (10, 4)
Kích thước của X_train_split 7: (10, 4)
Kích thước của X_train_split 8: (10, 4)
Kích thước của X_train_split 9: (10, 4)
Kích thước của X_train_split 10: (10, 4)


In [77]:
data = np.random.uniform(0, 10,(150, 5))
data.shape

(150, 5)

In [78]:
x = data[:, :-1]
y = data[:, -1]

x.shape, y.shape

((150, 4), (150,))

In [79]:
dataset_size = x.shape[0]
dataset_size

150

In [80]:
train_size = int(0.7 * dataset_size)
train_size

105

In [82]:
x_train = x[:train_size]
x_test = x[train_size:]

x_train.shape, x_test.shape

((105, 4), (45, 4))

In [83]:
split = x_train.shape[0]//10
split

10

In [84]:
for counter in range(0, x_train.shape[0], split):
    print(x_train[counter:counter + split].shape)

(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(5, 4)
