CƠ BẢN VỀ PYTORCH

Dataset with pytorch

In [9]:
import pandas as pd
import torch

df = pd.read_csv('iris.csv')

print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [7]:
df.shape

(150, 6)

In [10]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(["Species"], axis=1).values
y = le.fit_transform(df["Species"].values)

# Chia dữ liệu với test size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [12]:
print(f"train size {len(y_train)}")

train size 120


In [13]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [19]:
# Tạo một tensor với requirements_grad=True 
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [15]:
# Định nghĩa hàm 
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [23]:
# Bài tập 

# Cho = 5x^6 + 3x^3 + 2x^1 + x + 2x+5x^4 + 1

# Cho biết độ dốc của đa thức trên tại điểm nào
x = torch.tensor(2.0, requires_grad=True)

y = 5*x**6 + 3*x**3 + 2*x + 2*x + 5*x**4 + 1

y.backward()

print(x.grad)

tensor(1160.)


In [ ]:
# #BTVN 1:
# Tạo một tensor có giá trị ban đầu là 2.0

# Định nghĩa hàm số và tính gradiant 

# y = x^3 + 2x^2 + 5x + 1

# Hãy tính dy/dx tại giá trị của x 

# Dùng phương pháp Gradient Descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp

# BTVN 2:
    
# Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 - 10) và y là số điểm được tính theo công thức y = 3x + 5 + noise

# Với noise là một giá trị ngẫu nhiên nhỏ

# 1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad=True
# 2. Tính MSE
# 3. Tính gradient
# 4. Cập nhật tham số w và b bằng gradient Descent với Learning rate alpha = 0.01
# 5. Lặp lại quá trình trên trong 100 vòng lặp và quan sát sự hội tụ của mô hình



In [4]:
import torch

# Tạo tensor x với giá trị ban đầu là 2.0
x = torch.tensor([2.0], requires_grad=True)

# Định nghĩa hàm số y = x^3 + 2x^2 + 5x + 1
def y(x):
    return x**3 + 2*x**2 + 5*x + 1

alpha = 0.1

# Dùng phương pháp Gradient Descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp
for i in range(10):
    y_val = y(x)
    
    y_val.backward()
    
    with torch.no_grad():
        x -= alpha * x.grad
    
    x.grad.zero_()
    
    print(f"Vòng lặp {i+1}: x = {x.item()}, y = {y_val.item()}")

Vòng lặp 1: x = -0.5, y = 27.0
Vòng lặp 2: x = -0.875, y = -1.125
Vòng lặp 3: x = -1.2546875476837158, y = -2.513671875
Vòng lặp 4: x = -1.7250847816467285, y = -4.1001362800598145
Vòng lặp 5: x = -2.427826166152954, y = -6.807298183441162
Vòng lặp 6: x = -3.7249975204467773, y = -13.660883903503418
Vòng lặp 7: x = -6.897680282592773, y = -41.56037521362305
Vòng lặp 8: x = -18.912006378173828, y = -266.51019287109375
Vòng lặp 9: x = -119.14640808105469, y = -6142.375
Vòng lặp 10: x = -4330.74755859375, y = -1663589.5


In [3]:
import torch
import numpy as np

# Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 - 10) và y là số điểm được tính theo công thức y = 3x + 5 + noise
np.random.seed(42)
x_data = np.random.randint(1, 11, size=20)  
noise = np.random.normal(0, 1, size=20)     
y_data = 3 * x_data + 5 + noise            

x_data = torch.tensor(x_data, dtype=torch.float32)
y_data = torch.tensor(y_data, dtype=torch.float32)

# Cập nhật tham số w và b bằng gradient Descent với Learning rate alpha = 0.01
w = torch.tensor([0.0], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

alpha = 0.01

# Hàm tính MSE
def mse_loss(y_pred, y_true):
    return ((y_pred - y_true) ** 2).mean()

# Lặp lại quá trình trên trong 100 vòng lặp và quan sát sự hội tụ của mô hình
for i in range(100):
    y_pred = w * x_data + b
    
    # Tính MSE
    loss = mse_loss(y_pred, y_data)
    
    # Tính gradient
    loss.backward()
    
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
    
    w.grad.zero_()
    b.grad.zero_()
    
    if (i+1) % 10 == 0:
        print(f"Vòng lặp {i+1}: w = {w.item()}, b = {b.item()}, Loss = {loss.item()}")

Vòng lặp 10: w = 3.5914905071258545, b = 0.6310285925865173, Loss = 2.1363797187805176
Vòng lặp 20: w = 3.578610420227051, b = 0.7164723873138428, Loss = 2.061427593231201
Vòng lặp 30: w = 3.566049814224243, b = 0.799793004989624, Loss = 1.9901536703109741
Vòng lặp 40: w = 3.5538012981414795, b = 0.8810432553291321, Loss = 1.922379732131958
Vòng lặp 50: w = 3.5418572425842285, b = 0.9602745771408081, Loss = 1.8579308986663818
Vòng lặp 60: w = 3.530210018157959, b = 1.0375370979309082, Loss = 1.796645164489746
Vòng lặp 70: w = 3.5188519954681396, b = 1.1128798723220825, Loss = 1.738366723060608
Vòng lặp 80: w = 3.5077764987945557, b = 1.186350703239441, Loss = 1.682948112487793
Vòng lặp 90: w = 3.496975898742676, b = 1.257995843887329, Loss = 1.6302505731582642
Vòng lặp 100: w = 3.4864437580108643, b = 1.327860713005066, Loss = 1.5801390409469604


In [25]:
# Pytorch with tensor

import torch
import numpy as np

In [26]:
torch.__version__

'2.6.0+cpu'

In [27]:
# Chuyển đổi mảng numpy sang tensor pytorch 
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [28]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [29]:
print(x.dtype)

torch.int64


In [30]:
print(x.type())

torch.LongTensor


In [31]:
arr2 = np.arange(0.,12.).reshape(4,3)
print(arr2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [32]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [35]:
arr = np.arange(0, 5)
x = torch.from_numpy(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [ ]:
# BTVN 4: Giải thích lý do tại sao cho 2 trường hợp trên

# BTVN 4: Bạn hãy giúp thầy về nhà tạo tensor với:
# Empyty
# Zeros
# Ones
# Random
# Reshape với view và view as

# Deadline 15/3

In [5]:
import torch

# Empyty
empty_tensor = torch.empty(2, 3)
print("Empty Tensor:")
print(empty_tensor)

# Zeros
zeros_tensor = torch.zeros(2, 3)
print("\nZeros Tensor:")
print(zeros_tensor)

# Ones
ones_tensor = torch.ones(2, 3)
print("\nOnes Tensor:")
print(ones_tensor)

# Random
random_tensor = torch.rand(2, 3)
print("\nRandom Tensor:")
print(random_tensor)

# Reshape với view và view as
original_tensor = torch.arange(6)  
print("\nTensor gốc:")
print(original_tensor)

reshaped_tensor = original_tensor.view(2, 3)
print("\nReshaped Tensor (view):")
print(reshaped_tensor)

another_tensor = torch.zeros(3, 2)
reshaped_tensor_as = original_tensor.view_as(another_tensor)
print("\nReshaped Tensor (view as):")
print(reshaped_tensor_as)



Empty Tensor:
tensor([[8.4376e+34, 2.0221e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random Tensor:
tensor([[0.1689, 0.9219, 0.7951],
        [0.6026, 0.0044, 0.0657]])

Tensor gốc:
tensor([0, 1, 2, 3, 4, 5])

Reshaped Tensor (view):
tensor([[0, 1, 2],
        [3, 4, 5]])

Reshaped Tensor (view as):
tensor([[0, 1],
        [2, 3],
        [4, 5]])
